name: PHP_CodeSniffer

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd home/runner/work/1TravelSphere/1TravelSphere
          composer install

      - name: Install PHP_CodeSniffer
        run: composer require --dev squizlabs/php_codesniffer

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs
