name: PHP_CodeSniffer

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies and Lint
        run: |
          cd path/to/directory/with/composer.json
          composer install
          # Run your linter command here
        working-directory: home/runner/work/1TravelSphere/1TravelSphere

      - name: Install PHP_CodeSniffer
        run: composer require --dev squizlabs/php_codesniffer

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs
